#get spotify api keys stored in github repository secret settings in order for live site to work without entering keys in manually

# name: Deploy to GitHub Pages
# on: [push]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [13.2.0]
#     steps:
#       - name: Checkout
#         uses: actions/checkout@master

#       - name: Deploy to production
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         env:
#           AUTHOR: spk2dc
#           BUILD_PATH: public
#           BRANCH: master # The branch the action should deploy to.
#           GITHUB_PAGE_NAME: spk2dc.github.io
#           PA_TOKEN: ${{ secrets.PA_TOKEN }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
#           USERNAME: spk2dc
#           EMAIL: spk2dc@virginia.edu
#           CLIENT_ID: ${{ secrets.CLIENT_ID }}
#           CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          

###### source: https://github.com/marketplace/actions/deploy-your-app-to-github-pages ######
###### source: https://stackoverflow.com/questions/53648652/how-to-use-environment-variables-in-github-page ######
###### source: https://dev.to/pierresaid/deploy-node-projects-to-github-pages-with-github-actions-4jco ######
###### source: https://github.com/marketplace/actions/deploy-to-github-pages ######



###### source: https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets ######

# steps:
#   - name: Hello world action
#     with: # Set the secret as an input
#       super_secret: ${{ secrets.SuperSecret }}
#     env: # Or as an environment variable
#       super_secret: ${{ secrets.SuperSecret }}


###### source: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow ######

# jobs:
#   build:
#     # Job name is Greeting
#     name: Greeting
#     # This job runs on Linux
#     runs-on: ubuntu-latest
#     steps:
#       # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
#       - name: Hello world
#         uses: actions/hello-world-javascript-action@v1
#         with:
#           who-to-greet: 'Mona the Octocat'
#         id: hello
#       # This step prints an output (time) from the previous step's action.
#       - name: Echo the greeting's time
#         run: echo 'The time was ${{ steps.hello.outputs.time }}.'